# Matrix Buffer Issue

In [1]:
import slangpy as spy
import numpy as np

In [2]:
device = spy.create_device()

[INFO] (rhi) layer: CreateDevice: Debug layer is enabled.
[WARN] No supported shader model found, pretending to support sm_6_0.


In [3]:
mat_src = '''
float3x3 matFunc(int id){
    return float3x3(id);
}
'''
module = spy.Module.load_from_source(
    device,
    "mat_module",
    mat_src
)
module

slangpy.Module("mat_module", path="/Users/fangjun/Documents/stanford/bvhgs/notebooks/7bc67c88af84571134afe60c6102cbaebe494ef5")

In [4]:
res_buf = spy.NDBuffer(device, dtype="float3x3", shape=(2,))
module.matFunc(spy.call_id(), _result=res_buf)
res_buf

NDBuffer(shape=[2], dtype=matrix<float,3,3>)

In [5]:
arr = res_buf.to_numpy()
arr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)

In [6]:
arr = np.random.rand(2, 3, 3).astype(np.float32)
arr

array([[[0.7101268 , 0.31608027, 0.15534358],
        [0.12981576, 0.6235811 , 0.62952507],
        [0.38811255, 0.4645462 , 0.3867753 ]],

       [[0.7353049 , 0.917618  , 0.29001763],
        [0.15473478, 0.58377004, 0.35276458],
        [0.3132759 , 0.18290135, 0.37213787]]], dtype=float32)

In [7]:
res_buf.copy_from_numpy(arr)
res_buf.to_numpy()

array([[[0.7101268 , 0.31608027, 0.15534358],
        [0.12981576, 0.6235811 , 0.62952507],
        [0.38811255, 0.4645462 , 0.3867753 ]],

       [[0.7353049 , 0.917618  , 0.29001763],
        [0.15473478, 0.58377004, 0.35276458],
        [0.3132759 , 0.18290135, 0.37213787]]], dtype=float32)

In [8]:
arr_slice = np.random.rand(2, 4, 4)[:, :3, :3]
arr_slice

array([[[0.11923844, 0.82514376, 0.66905528],
        [0.67855391, 0.8258731 , 0.13383781],
        [0.91252327, 0.24859423, 0.77800662]],

       [[0.1240015 , 0.99457213, 0.89089964],
        [0.12488809, 0.73620953, 0.98599798],
        [0.78903827, 0.53465217, 0.66751952]]])

In [9]:
res_buf.copy_from_numpy(arr_slice)

RuntimeError: Source Numpy array must be contiguous
/Users/fangjun/Documents/stanford/bvhgs/external/slangpy/src/slangpy_ext/utils/slangpystridedbufferview.cpp:406 in function copy_from_numpy