In [1]:
import slangpy as spy
import numpy as np

In [2]:
device = spy.create_device()

[INFO] (rhi) layer: CreateDevice: Debug layer is enabled.
[WARN] No supported shader model found, pretending to support sm_6_0.


# Vector Buffer

In [3]:
vec_src = '''
float3 vecFunc(int id){
    return float3(id);
}
'''
module = spy.Module.load_from_source(
    device,
    "vec_module",
    vec_src
)
module

slangpy.Module("vec_module", path="/Users/fangjun/Documents/stanford/gslang/notebooks/playgrounds/275724cdf13a67f9b83966b12c37ba181cb8083b")

In [4]:
res_buf = spy.NDBuffer(device, dtype="float3", shape=(2,))
module.vecFunc(spy.call_id(), _result=res_buf)
res_buf.to_numpy()

array([[0., 0., 0.],
       [1., 1., 1.]], dtype=float32)

In [5]:
arr = np.random.rand(2, 3).astype(np.float32)
arr

array([[0.5334674 , 0.5868144 , 0.54378015],
       [0.54020894, 0.3814292 , 0.1466357 ]], dtype=float32)

In [6]:
res_buf.copy_from_numpy(arr)
res_buf.to_numpy()

array([[0.5334674 , 0.5868144 , 0.54378015],
       [0.54020894, 0.3814292 , 0.1466357 ]], dtype=float32)

In [7]:
cur = res_buf.cursor()

# Matrix Buffer

In [8]:
mat_src = '''
float3x3 matFunc(int id){
    return float3x3(id);
}
'''
module = spy.Module.load_from_source(
    device,
    "mat_module",
    mat_src
)
module

slangpy.Module("mat_module", path="/Users/fangjun/Documents/stanford/gslang/notebooks/playgrounds/5aa8941f078c5f3368a67f0ce8bbb2f8f5394964")

In [9]:
res_buf = spy.NDBuffer(device, dtype="float3x3", shape=(2,))
module.matFunc(spy.call_id(), _result=res_buf)
res_buf.to_numpy()

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)

In [10]:
arr = np.random.rand(2, 3, 3).astype(np.float32)
arr

array([[[0.62096876, 0.6000331 , 0.5168244 ],
        [0.07333853, 0.18640886, 0.03994429],
        [0.25229988, 0.04005325, 0.8297588 ]],

       [[0.84001416, 0.41784438, 0.96792066],
        [0.24740942, 0.26931885, 0.7677188 ],
        [0.60231185, 0.6055691 , 0.28619352]]], dtype=float32)

In [11]:
res_buf.copy_from_numpy(arr)
res_buf.to_numpy()

array([[[0.62096876, 0.6000331 , 0.5168244 ],
        [0.07333853, 0.18640886, 0.03994429],
        [0.25229988, 0.04005325, 0.8297588 ]],

       [[0.84001416, 0.41784438, 0.96792066],
        [0.24740942, 0.26931885, 0.7677188 ],
        [0.60231185, 0.6055691 , 0.28619352]]], dtype=float32)

In [12]:
cur = res_buf.cursor()

# High Dimensional Array Buffer

In [13]:
arr_src = '''
float[3][3][3] arrFunc(int id){
    float[3][3][3] res;
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            for (int k = 0; k < 3; k++)
                res[i][j][k] = id;
    return res;
}
'''
module = spy.Module.load_from_source(
    device,
    "arr_module",
    arr_src
)
module

slangpy.Module("arr_module", path="/Users/fangjun/Documents/stanford/gslang/notebooks/playgrounds/6aa4c753ff03aea8749eb6a26a846f592ef7bae7")

In [14]:
res_buf = spy.NDBuffer(device, dtype="float[3][3][3]", shape=(2,))
module.arrFunc(spy.call_id(), _result=res_buf)
res_buf.to_numpy()

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)

In [15]:
arr = np.random.rand(2, 3, 3, 3).astype(np.float32)
arr

array([[[[2.95586735e-01, 6.58214748e-01, 2.48779461e-01],
         [7.35950768e-01, 4.51477170e-01, 7.96792448e-01],
         [1.42369494e-01, 6.91270769e-01, 6.66874647e-02]],

        [[7.21891701e-01, 9.35117722e-01, 5.56373179e-01],
         [8.49500358e-01, 6.55330837e-01, 5.42824864e-01],
         [1.35916686e-02, 8.64656866e-01, 3.63121659e-01]],

        [[1.04723983e-01, 5.82146421e-02, 4.09046382e-01],
         [2.50726193e-01, 6.22263432e-01, 4.04875219e-01],
         [5.12597978e-01, 3.20555359e-01, 5.59708953e-01]]],


       [[[3.18059057e-01, 1.18895784e-01, 3.40780653e-02],
         [3.26812975e-02, 7.08671749e-01, 5.31820320e-02],
         [3.65011096e-01, 4.29071069e-01, 5.13449132e-01]],

        [[1.62176564e-01, 1.45894095e-01, 1.05733834e-01],
         [6.32239521e-01, 8.97526555e-03, 8.97764027e-01],
         [3.13489646e-01, 1.78640470e-01, 5.19784212e-01]],

        [[3.10566783e-01, 6.25437915e-01, 4.19199586e-01],
         [1.71693470e-02, 7.12767899e-01, 1.

In [16]:
cur = res_buf.cursor()

In [17]:
cur.element_type.col_count

0

In [18]:
res_buf.copy_from_numpy(arr)
res_buf.to_numpy()

array([[[[2.95586735e-01, 6.58214748e-01, 2.48779461e-01],
         [7.35950768e-01, 4.51477170e-01, 7.96792448e-01],
         [1.42369494e-01, 6.91270769e-01, 6.66874647e-02]],

        [[7.21891701e-01, 9.35117722e-01, 5.56373179e-01],
         [8.49500358e-01, 6.55330837e-01, 5.42824864e-01],
         [1.35916686e-02, 8.64656866e-01, 3.63121659e-01]],

        [[1.04723983e-01, 5.82146421e-02, 4.09046382e-01],
         [2.50726193e-01, 6.22263432e-01, 4.04875219e-01],
         [5.12597978e-01, 3.20555359e-01, 5.59708953e-01]]],


       [[[3.18059057e-01, 1.18895784e-01, 3.40780653e-02],
         [3.26812975e-02, 7.08671749e-01, 5.31820320e-02],
         [3.65011096e-01, 4.29071069e-01, 5.13449132e-01]],

        [[1.62176564e-01, 1.45894095e-01, 1.05733834e-01],
         [6.32239521e-01, 8.97526555e-03, 8.97764027e-01],
         [3.13489646e-01, 1.78640470e-01, 5.19784212e-01]],

        [[3.10566783e-01, 6.25437915e-01, 4.19199586e-01],
         [1.71693470e-02, 7.12767899e-01, 1.